### ISSUE TITLE
No Adventure Page

### ISSUE THREAD

**Issue by aniket-deole** [AceArthur/Catch-Your-Dragon#6]
According to the design document, after login, we should proceed to this page. But this page is nowhere to be seen. Is this an error/issue ?  Or is this functionality not implemented ?

<img width="505" alt="screen shot 2015-12-05 at 18 23 27" src="https://cloud.githubusercontent.com/assets/2942620/11610840/502175a0-9b7d-11e5-87a9-e1552b7747c7.png">

**Comment by aniket-deole** [comment]
Adventure page is now displayed.
Closing the issue.
<img width="1440" alt="screen shot 2015-12-05 at 18 30 25" src="https://cloud.githubusercontent.com/assets/2942620/11610864/4d38e372-9b7e-11e5-8f8c-e861d414392a.png">

**Comment by GoFlying** [comment]
Problem solved. Thanks.
