### ISSUE TITLE
Dragon is caught, but score is not displayed.

### ISSUE THREAD

**Issue by aniket-deole** [AceArthur/Catch-Your-Dragon#7]
According to the design document, the score must be displayed.
<img width="461" alt="screen shot 2015-12-05 at 18 26 12" src="https://cloud.githubusercontent.com/assets/2942620/11610848/bd63d90a-9b7d-11e5-8426-1d7f169d9e0a.png">
<img width="1440" alt="screen shot 2015-12-05 at 18 26 55" src="https://cloud.githubusercontent.com/assets/2942620/11610849/c5c6e9c0-9b7d-11e5-9c61-130aee9813c1.png">

**Comment by jianmengpei** [comment]
Now, it has been updated, please check it.

**Comment by aniket-deole** [comment]
Score is now displayed.!
