### ISSUE TITLE
Time is not displayed on the screen.

### ISSUE THREAD

**Issue by aniket-deole** [AceArthur/Catch-Your-Dragon#8]
Time should be displayed on the screen.

**Comment by tguo2** [comment]
First, we want to design this game with time limit, but in the process, we find it better to design it with the limitation of number of times of clicking the screen. So we add a 'Harmer:10' instead of Time, when you click once, the number will decrease by 1. Thanks for pointing out this problem.

**Comment by aniket-deole** [comment]
Instead of time, remaining chances are displayed.
I think this can be closed.
